# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1briJG9uvSlRgF6tLP_V9I6uASBNGCSU9
"""

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

#3
#1)
image = cv.imread('spine.tif',0)

#2)

def transform(imag,name,y=1):
    Imax=np.max(imag)
    Imin=np.min(imag)
    if name=='contrast':
      stretch_image=((imag - Imin)/(Imax - Imin))*255
      stretch_image=stretch_image.astype(image.dtype)
      return stretch_image
    elif name=='power':
      c=(Imax-1)**(1-y)
      power_image = c*(imag**y)
      power_image=power_image.astype(image.dtype)
      return power_image


#3)
powered_pic=transform(image,'power',0.5)
stretched_pic=transform(image,'contrast')
P_S=transform(powered_pic,'contrast')
S_P=transform(stretched_pic,'power',0.5)

#4)
plt.subplot(131)
plt.imshow(image, cmap = 'gray', vmin=0, vmax=255)
plt.title('original')
plt.axis('off')

plt.subplot(232)
plt.imshow(powered_pic, cmap = 'gray', vmin=0, vmax=255)
plt.title('power')
plt.axis('off')

plt.subplot(233)
plt.imshow(stretched_pic, cmap = 'gray', vmin=0, vmax=255)
plt.title('stretch')
plt.axis('off')

plt.subplot(235)
plt.imshow(P_S, cmap = 'gray', vmin=0, vmax=255)
plt.title('power-stretch')
plt.axis('off')

plt.subplot(236)
plt.imshow(S_P, cmap = 'gray', vmin=0, vmax=255)
plt.title('stretch-power')
plt.axis('off')