# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fsMo-kJsKeYg2N2MBzBUTzqnrtmnthXK
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
frames=np.zeros((256,256))
cap = cv2.VideoCapture('MRI-Head.avi')
length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
i=1
while cap.isOpened():
    ret,frame=cap.read()
    if not ret:
      break
    frame=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    frames=frames+frame
    if i==1:
      first_frame=frame
    i+=1

cv2_imshow(first_frame)
cv2_imshow(frames/length)
cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()
#ب
mask1=np.load('mask1.npy')
mask2=np.load('mask2.npy')
pic=mask1*(frames/length)+mask2*(frames/length)
cv2_imshow(pic)
cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()