# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fsMo-kJsKeYg2N2MBzBUTzqnrtmnthXK
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img=cv2.imread('transformed.png',0)
cv2_imshow(img)
rows,cols = img.shape
print(rows,cols)
M = np.float32([[1,0,128],[0,1,64]])
dst = cv2.warpAffine(img,M,(cols,rows))

cv2_imshow(dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

dst = np.pad(dst, pad_width=[(256, 256),(256, 256)], mode='constant')
cv2_imshow(dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
#
T = np.float32([[1,0,250],[0,1,-100]])
translated_pic=cv2.warpAffine(dst,T,(1024,1024))
cv2_imshow(translated_pic)
cv2.waitKey(0)
cv2.destroyAllWindows()
#
s= np.float32([[1,-0.3,0],[0.,1,0]])
sheared = cv2.warpAffine(dst,s,(1024,1024))
cv2_imshow(sheared)
cv2.waitKey(0)
cv2.destroyAllWindows()
#
theta = np.radians(20)
c, s = np.cos(theta), np.sin(theta)
R=np.float32([[c,-s,0],[s,c,0]])
rotated=cv2.warpAffine(dst,R,(1024,1024))
cv2_imshow(rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()